name: neoforge

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changelog
        uses: ssblur/git-changelog-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build Forge
        run: bash ./gradlew neoforge:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: 'ssblur'
      - name: Cleanup
        run: |
          rm */build/libs/scriptor-*-dev-shadow.jar
          bash -c 'for file in neoforge/build/libs/*.jar; do mv "$file" "${file%.jar}-neoforge.jar"; done'
      - name: Extract Tag Version
        id: tag
        run: echo "version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: Deploy
        uses: ssblur/minecraft-publish@v1
        with:
          mod-file: neoforge/build/libs/scriptor-${{ steps.tag.outputs.version }}-neoforge.jar
          version-name: "${{ steps.tag.outputs.version }}-neoforge"
          minecraft-version: 1.20.6
          mod-loader: neoforge
          changelog: ${{ steps.changelog.outputs.changelog }}
          dependencies: |
            architectury-api

          github-token: ${{ secrets.GITHUB_TOKEN }}

          curse-project-id: "817436"
          curse-token: "${{ secrets.CURSEFORGE_TOKEN }}"
          curse-relations: "architectury-api:requiredDependency"

          modrinth-project-id: "scriptor-magicae"
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

          jar-signing-store: ${{ secrets.JAR_SIGNING_STORE }}
          jar-signing-alias: ${{ secrets.JAR_SIGNING_ALIAS }}
          jar-signing-store-pass: ${{ secrets.JAR_SIGNING_STORE_PASS }}
          jar-signing-key-pass: ${{ secrets.JAR_SIGNING_KEY_PASS }}